#!/bin/bash

set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Stop the service before removing
        systemctl stop godhcp.service || true
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
